### ISSUE TITLE
Fee rate

### ISSUE THREAD

**Issue by RapidEU** [gensleralexander/JACB#1]
Hiya, awesome tool for backtesting, love it!

I was wondering maybe if you could add custom fee values for the calculation of the back testing and also real market trading, it should be calculated by a define able setting. (some people got some vip lvls and use BNB for trading, so those 2 things should be an option)

**Comment by gensleralexander** [comment]
Hey, thank you for your feedback.
I will add your feature request in the next release.
Please note, that this may take a few days as I am currently not at home.

**Comment by gensleralexander** [comment]
Added this in [build 565](https://github.com/gensleralexander/JACB/releases/tag/0.9.565)
Let me know if you need anything else.
