### ISSUE TITLE
Backtesting chart

### ISSUE THREAD

**Issue by Hulkstance** [gensleralexander/JACB#2]
Hello!

I like that project and it helped me a lot on mine, thanks to @gensleralexander. I was wondering if there is a chart diagram for backtesting, similar to the one below. I mean overall if you know something. Basically, it's a candlestick chart with red/green dots for buy/sell orders.

I look forward hearing from you.

![backtesting graphics](https://user-images.githubusercontent.com/33224919/73054815-0947be00-3e94-11ea-9d89-b033f23ef4a7.png)

**Comment by gensleralexander** [comment]
Hello @Hulkstance 
I'm a little bit confused about your question, isn't this diagram exactly like mine, when you hide the indicators?

![image](https://user-images.githubusercontent.com/46425719/73057187-2464fe80-3e91-11ea-9343-2629f3e662fe.png)

So I believe this should be the same technique as I use, a simple chart diagram with two layers.
I use Syncfusion for this, but you can pretty much use every chart framework for this:

See [line 220](https://github.com/gensleralexander/JACB/blob/master/JACB.UWP/Views/Backtest.xaml)
I have two static layers, the first one for the candles (Candle Series), and the second for the backtest results (Bubble Series)
I also add dynamically charts for the Technical Indicators, however this is written in C# code and not in the XAML.

If you have further questions, feel free to ask.

Side note on your strategy: though the overall result of +58% (~14% gain without including market gains) is good, it seems like there are a lot of "useless trades" in there. I don't know if this app includes the fees, but I would tend to say, that the fees gonna eat up a lot of your returns. If the app provides something like my "do-nothing strategies", try to eliminate some of these "useless trades".
